Implementation of cd and ls
Fatalll/Software_Design pull request #4
Opened 2019-03-10 20:43 UTC by TanVD

Pros: 
* Easy to add a new command
* Support of working-dir change out of the box
* Good documentation and architecture

Cons:
* Arguments CLI library supported only for Grep

2019-05-12 14:27 UTC, artbez requested changes

2019-05-12 14:27 UTC, artbez commented on cli/tests/test_command_ls.py
> +class TestCommandCd(TestCase):
Нужно переименовать в TestCommandLs

2019-05-12 14:27 UTC, artbez commented on cli/tests/test_command_cd.py
> +        self.assertEqual(os.getcwd(), os.path.dirname(os.path.dirname(__file__)))
Хорошо бы добавить еще парочку тестов: 
1) cd ..
2) cd <реально существующая директория>
3) cd <не существующая директория>

2019-05-12 14:29 UTC, artbez requested changes

2019-05-12 14:29 UTC, artbez commented on cli/tests/test_command_ls.py
> +class TestCommandCd(TestCase):
А еще он фейлится на трависе

2019-06-12 13:40 UTC, TanVD commented on cli/tests/test_command_ls.py
> +class TestCommandCd(TestCase):
Fixed

2019-06-12 13:46 UTC, TanVD commented on cli/tests/test_command_cd.py
> +        self.assertEqual(os.getcwd(), os.path.dirname(os.path.dirname(__file__)))
Fixed

2019-06-12 13:59 UTC, TanVD commented
Поправил все замечания @artbez

2019-06-13 21:14 UTC, artbez approved these changes

2019-06-18 16:23 UTC, yurii-litvinov commented
Окей, зачтена

2019-06-20 15:20 UTC, closed without merging